### ISSUE TITLE
Error with grep BSD version 

### ISSUE THREAD

**Issue by estyxx** [darvid/zsh-poetry#1]
The grep installed on osx doesn't have the "-P" (Perl regex) option.  
```
grep -V 
grep (BSD grep) 2.5.1-FreeBSD
```

Using `sed` [here](https://github.com/darvid/zsh-poetry/blob/43162ebeb783105717cb71e8752527946afbd1b7/poetry.zsh#L17)  instead of grep should fix it: 
```
venv=$(command poetry debug:info 2>/dev/null | sed -n "s/\* Path: +\t*\(.*\)/\1/p")
venv=${path_venv##* }
```

But the name of the poetry venv does not appear anyway...

**Comment by darvid** [comment]
ahh, good catch. I'll have to hunt down an osx machine to test with.

> But the name of the poetry venv does not appear anyway...

could you elaborate a bit on this please? does it fail to activate? is `VIRTUAL_ENV` set/unset in a poetry project directory?

**Comment by estyxx** [comment]
No, The $VIRTUAL_ENV variable is empty, who should set it?

 I was inside a directory with `pyproject.toml`, I fixed locally the petry.zsh file (as I mentioned above) to be able to run your tool... 
And [maybe I did not understand the purpose of this tool... sorry if I did...] I was expecting to visualize the name of the activate poetry environment in the prompt element with [powerlevel9k](https://github.com/Powerlevel9k/powerlevel9k) like anaconda does... Maybe it's a feature :) 
or print something at least...

**Comment by darvid** [comment]
`VIRTUAL_ENV` should be set automatically after `cd`ing to a directory with a pyproject.toml file, if this plugin worked correctly and sourced the poetry `bin/activate` script. if it's not, then I'm guessing something went wrong with that...

this plugin doesn't actually output anything, but poetry+virtualenv itself should update your prompt when activated. I'm a powerlevel user too (👊), and the [virtualenv prompt segment](https://github.com/Powerlevel9k/powerlevel9k#virtualenv) picks up my venv correctly, on Linux at least.

could you try maybe putting some echo statements to show the value of `$venv` after your modifications above? I'm curious if `${venv}/bin/activate` exists? also what's your poetry version?

**Comment by estyxx** [comment]
Ok, I understood the problems:
1. I removed "virtalenv" from the PROMT_ELEMENTS because I was using anaconda 
2.  Poetry wasn't installed globally... -.- 
Definitely changing the venv grep should resolve the problem...
```
venv=$(command poetry debug:info 2>/dev/null | sed -n "s/\ *\* Path:\ *\(.*\)/\1/p")
```

**Comment by darvid** [comment]
ahh, cool. thanks for the fix!
