### ISSUE TITLE
Silently fail if pyproject.toml doesn't use poetry

### ISSUE THREAD

**Issue by JasonGrace2282** [darvid/zsh-poetry#15]
## Current Behavior
Poetry yells about there being no `[tool.poetry]` in the pyproject.toml

## Expected
There should be no output.

## (Temporary?) Fix
Add the following code before defining `venv` in `poetry.zsh`:
```bash
# if pyproject doesn't use poetry fail silently
if [[ "$(poetry env list &> /dev/null; echo $?)" != "0" ]]; then
  return 1
fi
```
If there are concerns, this behavior should be toggleable via some environment variable.

**Comment by NeilGirdhar** [comment]
Do you want to create a PR?
